코테2
-- 코드를 입력하세요
SELECT DISTINCT p.ID, p.NAME FROM PLACES as p LEFT JOIN SCHEDULES as s ON p.ID = s.PLACE_ID WHERE DATE_FORMAT(SCHEDULED_AT, '%Y-%m-%d') = '2019-01-06' and EXISTS(SELECT * FROM PLACE_REVIEWS as r WHERE r.PLACE_ID=p.ID)
